---
- hostname: dummy
  config:
    user: dummy 
    identifier: 0.0.0.0
    port: 22
    key: /dummy/i/am/dum
    source: /dummy/i/am/dum
    destination: /dummy/i/am/dum
    cron_schedule: "0 0 0 * * *"

