---
- user: ditto 
  identifier:
    Ip: 192.168.1.47
  port: 22
  key_path: /home/dto/.ssh/ditto
  source: /home/ditto/secs
  destination: /home/dto/backups
  frequency_hrs: 24.0
  incremental: true
