---
- user: cbroo 
  identifier:
    Ip: 192.168.1.47
  port: 22
  key_path: /home/bam/.ssh/oorbc
  source: /home/cbroo/secs
  destination: /home/bam/backups
  frequency_hrs: 24.0
  incremental: true
